# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/webui"
    schedule:
      interval: "daily"
    versioning-strategy: "increase-if-necessary"
    allow:
      - dependency-type: direct
      - dependency-type: development
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/yamlcli"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5

  - package-ecosystem: "gomod"
    directory: "/ruleconverter"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
